spring:
  profiles:
    active: local

  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:h2:~/quizle;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        #use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace